server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.0.252:3306/xyzw?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: guofei1314.
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xyzw.webhelper.auth,com.xyzw.webhelper.xyzw
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    com.xyzw.webhelper: INFO
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

jobs:
  dispatcher:
    tick-ms: 10000
  batch-daily:
    enabled: true
    cron: "0 10 12 * * *"
  token-refresh:
    enabled: true
    cron: "0 30 3 */5 * *"
  token-maintenance:
    enabled: true
    cron: "0 0 */5 * * *"
    enable-bottle-restart: true
