server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.0.252:3306/xyzw?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: guofei1314.
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xyzw.webhelper.auth,com.xyzw.webhelper.xyzw
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.xyzw.webhelper: INFO
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
